development:
  adapter: postgresql
  database: automecanicapalermo_development
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: automecanicapalermo_test
  host: localhost
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: automecanicapalermo_production
  pool: 5
  username: postgres
  password: postgres
